[package]
name = "actix-diesel-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7.0"
serde = { version = "1.0.204", features = ["derive"] }
diesel = { version = "2.2.0", features = ["postgres", "r2d2"] }
dotenvy = "0.15"
ulid = "1.1.3"
